apiVersion: v1
kind: Namespace
metadata:
  name: opensandbox-system
  labels:
    app.kubernetes.io/part-of: opensandbox
---
apiVersion: v1
kind: Namespace
metadata:
  name: opensandbox
  labels:
    app.kubernetes.io/part-of: opensandbox
